### ISSUE TITLE
COM Error 0x80bb0005: E_IPRT-ERRO

### ISSUE THREAD

**Issue by tiankangbo2019** [zrax/libvbox#8] opened 2023-10-02 15:22 UTC
Hello Michael Hansen, I have found that the launchVMProcess function of virtualbox cannot be executed and always reports the error "COM Error 0x80bb0005: E_IPRT-ERROR". I have tried upgrading to multiple versions of virtualbox 6 and 7, but I still cannot start the virtual machine. Have you tried to start the virtual machine in a Linux environment?

    auto vboxClient = VBox::virtualBoxClient();
    auto vbox = vboxClient->virtualBox();
    auto machines = vbox->machines();
    for (const auto &machine : machines)
        std::wcout << VBox::utf16ToWide(machine->name()) << std::endl;

    std::u16string tmp = u"";
    std::vector<std::u16string> u16x;
    u16x.push_back(tmp);

    auto session = vboxClient->session();
    auto machine = vbox->findMachine(u"ubuntu");

    if (machine) {
        auto progress = machine->launchVMProcess(session, u"gui", u16x);
        progress->waitForCompletion(-1);

    }

**Comment by zrax** [comment] 2023-10-02 18:00
Duplicate of #7

**Closed as completed by zrax** 2023-10-02 18:00 UTC
